### Basic Python Operations

In [2]:
s = "Hi there Sam!"
l = []
l = s.split()
l

['Hi', 'there', 'Sam!']

In [3]:
# Variable printing
planet = "Earth"
diameter = 12742

print("The diameter of the {} is {} kilometers".format(planet,diameter))

The diameter of the Earth is 12742 kilometers


In [4]:
# Nested Lists
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst[3][1][2][0]

'hello'

In [5]:
# Using Lamda to filter words that start with S
seq = ['soup','dog','salad','cat','great']

list(filter(lambda word: word[0]=='s',seq))

['soup', 'salad']

### Numpy 

In [7]:
import numpy as np

In [13]:
# All zero array
print(np.zeros(10))

# An array of fives
print(np.ones(10) * 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
# Creating a Matrix
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
# Row, then column selection
print(arr_2d[1,0])

# Selecting a section from the top right corner
print(arr_2d[:2,1:])

20


[[10 15]
 [25 30]]


In [17]:
# Identity Matrix
print(np.identity(3))

print('\n')

# Standard Normal Distribution
print(np.random.normal(0,1,25))

print('\n')

# Using arrange to build a (5 x 5) matrix
mat = np.arange(1,26).reshape(5,5)
mat

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[ 0.31948968  0.43294326 -1.35225679  1.11913535  1.61946113  0.13626539
  0.97475756 -2.20374862  0.12668335  0.41469132 -1.08525371  0.98953307
 -0.5912185  -0.35484547  0.32407695  1.6521075  -0.71393952  0.01570355
  0.21544923 -0.25668928 -0.47566674 -0.12299213 -0.43144187 -0.20208912
 -0.15573858]




array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
# Sum/Standard Deviation/Summing along columns
print(np.sum(mat))
print(np.std(mat))
print(np.sum(mat, axis = 0))

325
7.211102550927978
[55 60 65 70 75]


### Common Pandas Operations

In [23]:
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [29]:
# Building a DF
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [30]:
# Dropping a column (don't forget inplace = True)
df.drop('Z', axis=1, inplace=True)
df

W         X         Y
A -0.993263  0.196800 -1.136645
B  1.025984 -0.156598 -0.031579
C  2.154846 -0.610259 -0.755325
D  0.147027 -0.479448  0.558769
E -0.925874  1.862864 -1.133817

In [31]:
# Using loc (Can Select both rows and columns)
df.loc[['A','B'],['W','Y']]

W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579

In [32]:
# Conditional selection (Will remove everything less than 0 in the W column)
df[df['W']>0]

W         X         Y
B  1.025984 -0.156598 -0.031579
C  2.154846 -0.610259 -0.755325
D  0.147027 -0.479448  0.558769

In [33]:
# Printing out columns based on the W > 0 Condition
df[df['W']>0][['Y','X']]

Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [42]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

df_h = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df_h

A         B
G1 1 -1.382920  1.482495
   2  0.961458 -2.141212
   3  0.992573  1.192241
G2 1 -1.046780  1.292765
   2 -1.467514 -0.494095
   3 -0.162535  0.485809

In [43]:
# Just snagged the G1 section with loc
df_h.index.names = ['Group','Num']
df_h

A         B
Group Num                    
G1    1   -1.382920  1.482495
      2    0.961458 -2.141212
      3    0.992573  1.192241
G2    1   -1.046780  1.292765
      2   -1.467514 -0.494095
      3   -0.162535  0.485809

In [49]:
# Returns a Cross Section of the values
df_h.xs('G1')

A         B
Num                    
1   -1.382920  1.482495
2    0.961458 -2.141212
3    0.992573  1.192241

In [50]:
df1 = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

# Dropping rows
df1.dropna()

A    B  C
0  1.0  5.0  1

In [51]:
df1 = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

# Dropping Columns (You can also set the threshold with thresh = x)
df1.dropna(axis=1)

C
0  1
1  2
2  3

In [53]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

df2 = pd.DataFrame(data)
df2

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [54]:
# Creating a grouped DF
by_comp = df2.groupby("Company")
by_comp.head()

In [57]:
# Aggreating the mean, Pandas has many functions including count and sum.
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0