## General R Commands

In [1]:
# Printing
sprintf("%s is %f feet tall", "Sven", 7.1)

[1] "Sven is 7.100000 feet tall"

In [2]:
# Checking the class of a variable
x <- 5
class(x)

[1] "numeric"

In [3]:
# Assigning Names to a vector
days <- c('Mon','Tue','Wed','Thu','Fri','Sat','Sun')
temps2 <- c(70,73,80,82,76,67,70)
names(temps2) <- days
temps2

Mon Tue Wed Thu Fri Sat Sun 
 70  73  80  82  76  67  70

### If Statements, For Loops, and Functions

In [4]:
# x variable for if statement
x <-2

In [5]:
# Try changing the value above to learn the loop
if (x >= 5) {
    print("x is at least 5")
} else if (3 <= x & x < 5) {
    print("x is between 3 and 5")
} else {
    print("x is less than 3")
}

[1] "x is less than 3"


In [6]:
# Creating the vector
v <- c(1,2,3,4,5)

# Basic for Loop
for (i in v){
    print(sprintf("The number is %i", i))
}

[1] "The number is 1"
[1] "The number is 2"
[1] "The number is 3"
[1] "The number is 4"
[1] "The number is 5"


In [7]:
# Making a Function (Multiplies two inputs together)
prod <- function(int1,int2){
    return (int1*int2)
}

In [8]:
# Calling a function
prod(2,2)

[1] 4

In [9]:
# Applying a function over the vector v
prod(2, v)

[1]  2  4  6  8 10

In [10]:
# Another example, returning the number of times a number occurs in a vector
num_count <- function(int,vector){
    count = 0
    for (i in vector){
        if (i == int){
            count <- count+1
        }
    }
    return(count)
}

In [11]:
num_count(2,c(1,1,2,2,3,3))

[1] 2

### Time Stamps

In [12]:
# YYYY-MM-DD
as.Date('1990-11-03')

[1] "1990-11-03"

In [13]:
# Using Format
as.Date("Nov-03-90",format="%b-%d-%y")

[1] "1990-11-03"

In [14]:
as.POSIXct("11:02:03",format="%H:%M:%S")

[1] "2020-04-10 11:02:03 EDT"

### Vector Operations

In [15]:
v <- c(12,45,100,2)

In [16]:
# Checking the variable type, this can also be done with lists.
is.vector(v)

[1] TRUE

In [17]:
# Standard Deviation
sd(v)

#Variance
var(v)

# Maximum Element
max(v)

[1] 44.16918

[1] 1950.917

[1] 100

### Matrix Basics

In [18]:
# Creating two one row Matricies
A <- matrix(1:3, nrow =1)
B <- matrix(4:6, nrow =1)

In [19]:
# Row Binding
C <- rbind(A,B)
C

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [20]:
# Using column bind
D <- cbind(A,B)
D

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4    5    6

In [21]:
# Creating a 25 element matrix in order
mat2 <- matrix(1:25, byrow=TRUE, nrow=5 )
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [22]:
# Selecting elements
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [23]:
# Creating a random matrix using runif
ranmat <- matrix(runif(20,min=0,max=100),nrow = 4)
ranmat

[,1]      [,2]     [,3]     [,4]     [,5]    
[1,] 51.717195 30.82864 36.96350 40.72080 88.37495
[2,] 61.779495 76.69953 34.44216 65.44393 40.63352
[3,]  3.586155 88.61843 36.03530 46.44732 20.65443
[4,] 88.364412 10.74802 30.97616 22.52483 87.30880

### Dataframes 
#### Using mtcars, a built in R DataFrame

In [24]:
# Dataframe about states
head(mtcars, 3)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

In [25]:
# Dataframe structure
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [26]:
# Statistical summary of each column
summary(mtcars)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

In [27]:
# Getting the dimensions
dim(mtcars)

[1] 32 11

In [28]:
# Mean MPG
mean(mtcars$mpg)

[1] 20.09062

In [29]:
# Selecting only the rows with 6 cylinders
mtcars[mtcars$cyl == 6,]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Valiant        18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Merc 280       19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C      17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6

In [30]:
# Selecting specific columns (head to limit printing)
head(mtcars[, c('am','gear','carb')])

am gear carb
Mazda RX4         1  4    4   
Mazda RX4 Wag     1  4    4   
Datsun 710        1  4    1   
Hornet 4 Drive    0  3    1   
Hornet Sportabout 0  3    2   
Valiant           0  3    1

In [31]:
# Validating that I had not overwritten the earlier mtcars DF 
head(mtcars,3)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

In [32]:
# The above command can also be completed with the subset command
# Selecting cars with only 6 cylinders
subset(mtcars, cyl == 6)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Valiant        18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Merc 280       19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C      17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6

In [33]:
# Creating a new column and rounding it.
mtcars$performance <- mtcars$hp/mtcars$wt
mtcars$performance = round(mtcars$performance, digits =2)
head(mtcars,1)

mpg cyl disp hp  drat wt   qsec  vs am gear carb performance
Mazda RX4 21  6   160  110 3.9  2.62 16.46 0  1  4    4    41.98

In [34]:
# Subsetting for cars with more than 100hp and a weight of more than 2.5 tons. Then finding the average.
new_df <- mtcars[mtcars$hp > 100 & mtcars$wt >2.5,]
mean(new_df$mpg)

[1] 16.86364

In [35]:
# Selecting a specific element
mtcars['Hornet Sportabout',]

mpg  cyl disp hp  drat wt   qsec  vs am gear carb performance
Hornet Sportabout 18.7 8   360  175 3.15 3.44 17.02 0  0  3    2    50.87

### Dataframe merging example

In [36]:
## Building the two dataframes
authors <- data.frame(
    surname = I(c("Tukey", "Venables", "Tierney", "Ripley", "McNeil")),
    nationality = c("US", "Australia", "US", "UK", "Australia"),
    deceased = c("yes", rep("no", 4)))

books <- data.frame(
    name = I(c("Tukey", "Venables", "Tierney",
             "Ripley", "Ripley", "McNeil", "R Core")),
    title = c("Exploratory Data Analysis",
              "Modern Applied Statistics ...",
              "LISP-STAT",
              "Spatial Statistics", "Stochastic Simulation",
              "Interactive Data Analysis",
              "An Introduction to R"),
    other.author = c(NA, "Ripley", NA, NA, NA, NA,
                     "Venables & Smith"))

In [37]:
# Merging them togehter
m1 <- merge(authors, books, by.x = "surname", by.y = "name")
m1

surname  nationality deceased title                         other.author
1 McNeil   Australia   no       Interactive Data Analysis     NA          
2 Ripley   UK          no       Spatial Statistics            NA          
3 Ripley   UK          no       Stochastic Simulation         NA          
4 Tierney  US          no       LISP-STAT                     NA          
5 Tukey    US          yes      Exploratory Data Analysis     NA          
6 Venables Australia   no       Modern Applied Statistics ... Ripley

### Using dplyr

#### Common Operations 
filter() or slice()</br>
arrange()</br>
select() or rename()</br>
distinct()</br>
mutate() or transmute()</br>
summarise()</br>
sample_n() or sample_frac()</br>

In [38]:
library(dplyr)

Warning message:
"package 'dplyr' was built under R version 3.6.3"

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union




In [39]:
# Selecting the distinct gear values
distinct(select(mtcars,gear))

gear
1 4   
2 3   
3 5

In [40]:
# Removing the performance column from earlier
head(within(mtcars, rm(performance)), 3)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

In [41]:
# Recreating the performance column with dplyr
head(mutate(mtcars, perfomance = hp/wt), 3)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb performance perfomance
1 21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    41.98       41.98473  
2 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    38.26       38.26087  
3 22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    40.09       40.08621

In [42]:
# Summarising the mpg
summarise(mtcars, avg_mpg =mean(mpg, na.rm=TRUE))

avg_mpg 
1 20.09062

In [43]:
# Summarizing the average hp for 6 cylinder vehicles
mtcars %>% filter(cyl==6) %>% summarise(avg_hp = mean(hp))

avg_hp  
1 122.2857